@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.thenextlvl.hologram.v1_19_R3;

import core.annotation.MethodsReturnNonnullByDefault;
import core.annotation.ParametersAreNonnullByDefault;