@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.thenextlvl.hologram.api;

import core.annotation.MethodsReturnNonnullByDefault;
import core.annotation.ParametersAreNonnullByDefault;