@MethodsReturnNotNullByDefault
@ParametersAreNotNullByDefault
package net.thenextlvl.hologram.v1_20_R2.line;

import core.annotation.MethodsReturnNotNullByDefault;
import core.annotation.ParametersAreNotNullByDefault;