@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.thenextlvl.hologram;

import core.annotation.MethodsReturnNonnullByDefault;
import core.annotation.ParametersAreNonnullByDefault;